ServerEvents.recipes(event => {
    event.custom({
        type: "extendedcrafting:shaped_table",
        result: {id: "extendedcrafting:the_ultimate_ingot", count: 1},
        pattern: [
            "ABCDEFG",
            "HIJKLMN",
            "OPQRSTU",
            "VWXYZab",
            "cdefghi",
            "jklmnop",
            "qrstuvw"
        ],
        key: {
            A: {item: "minecraft:iron_ingot"},
            B: {item: "minecraft:gold_ingot"},
            C: {item: "minecraft:copper_ingot"},
            D: {item: "mekanism:ingot_osmium"},
            E: {item: "mekanism:ingot_steel"},
            F: {item: "mekanism:ingot_bronze"},
            G: {item: "mekanism:ingot_refined_obsidian"},
            H: {item: "mekanism:ingot_refined_glowstone"},
            I: {item: "mekanism:ingot_tin"},
            J: {item: "mekanism:ingot_lead"},
            K: {item: "industrialforegoing:pink_slime_ingot"},
            L: {item: "immersiveengineering:ingot_aluminum"},
            M: {item: "immersiveengineering:ingot_lead"},
            N: {item: "immersiveengineering:ingot_silver"},
            O: {item: "immersiveengineering:ingot_nickel"},
            P: {item: "immersiveengineering:ingot_uranium"},
            Q: {item: "immersiveengineering:ingot_constantan"},
            R: {item: "immersiveengineering:ingot_electrum"},
            S: {item: "immersiveengineering:ingot_steel"},
            T: {item: "mysticalagriculture:prosperity_ingot"},
            U: {item: "mysticalagriculture:inferium_ingot"},
            V: {item: "mysticalagriculture:prudentium_ingot"},
            W: {item: "mysticalagriculture:tertium_ingot"},
            X: {item: "mysticalagriculture:imperium_ingot"},
            Y: {item: "mysticalagriculture:supremium_ingot"},
            Z: {item: "mysticalagriculture:soulium_ingot"},
            a: {item: "minecraft:iron_ingot"},
            b: {item: "minecraft:gold_ingot"},
            c: {item: "minecraft:copper_ingot"},
            d: {item: "mekanism:ingot_osmium"},
            e: {item: "mekanism:ingot_steel"},
            f: {item: "mekanism:ingot_bronze"},
            g: {item: "mekanism:ingot_refined_obsidian"},
            h: {item: "mekanism:ingot_refined_glowstone"},
            i: {item: "mekanism:ingot_tin"},
            j: {item: "mekanism:ingot_lead"},
            k: {item: "industrialforegoing:pink_slime_ingot"},
            l: {item: "immersiveengineering:ingot_aluminum"},
            m: {item: "immersiveengineering:ingot_lead"},
            n: {item: "immersiveengineering:ingot_silver"},
            o: {item: "immersiveengineering:ingot_nickel"},
            p: {item: "immersiveengineering:ingot_uranium"},
            q: {item: "immersiveengineering:ingot_constantan"},
            r: {item: "immersiveengineering:ingot_electrum"},
            s: {item: "immersiveengineering:ingot_steel"},
            t: {item: "mysticalagriculture:prosperity_ingot"},
            u: {item: "mysticalagriculture:inferium_ingot"},
            v: {item: "mysticalagriculture:prudentium_ingot"},
            w: {item: "mysticalagriculture:tertium_ingot"}
        }
    }).id('kubejs:extendedcrafting/the_ultimate_ingot');
});